services:
  node:
    image: ts-migration
    container_name: ts-migration
    platform: linux/arm64
    working_dir: /app
    build: .
    ports:
      - 5173:5173
    volumes:
      - .:/app/
      - node_modules:/app/node_modules
    command: npm run dev

volumes:
  node_modules:
    driver: local
